package com.kjh.groupware.global.audit;

public enum AuditActionType {
    LOGIN,
    LOGIN_FAIL,
    CREATE,
    UPDATE,
    DELETE,
    READ,
    DOWNLOAD,
    SUBMIT,
    AGREE,
    APPROVE,
    REJECT,
    WITHDRAW,
    REDRAFT,
    CANCEL,
    RECEIVE,
    COMPLETE_RECEIPT,
    PRINT_PDF,
    ACCESS_DENIED,
    CHANGE_APPROVAL_LINE,
    SET_DELEGATION,
    CANCEL_DELEGATION,
    DELETE_APPROVAL,
    RESTORE_APPROVAL,
    CORRECT_APPROVAL_STATUS
}
