package com.kjh.groupware.domain.approval;
import com.fasterxml.jackson.databind.ObjectMapper; import com.kjh.groupware.domain.approval.dto.*; import com.kjh.groupware.domain.emp.*; import com.kjh.groupware.global.audit.*; import com.kjh.groupware.global.exception.BusinessException; import com.kjh.groupware.global.security.CurrentEmpProvider; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class BereavementPolicyService{
 private final BereavementPolicyRepository repository; private final CurrentEmpProvider current; private final EmployeePermissionService permissions; private final AuditLogService audit; private final ObjectMapper mapper;
 @Transactional(readOnly=true) public List<BereavementPolicyResponse> list(){requireManager();return repository.findAllByOrderByEventTypeAscFamilyRelationAscEffectiveFromDesc().stream().map(BereavementPolicyResponse::from).toList();}
 @Transactional(readOnly=true) public List<BereavementOptionResponse> options(java.time.LocalDate date){return repository.findAllEffective(date).stream().map(BereavementOptionResponse::from).toList();}
 @Transactional public BereavementPolicyResponse create(BereavementPolicyRequest r,String ip,String agent){Emp actor=requireManager();Normalized n=validate(r,null);BereavementPolicy p=repository.saveAndFlush(new BereavementPolicy(n.event(),n.relation(),r.allowedDays(),pay(r.payType()),r.evidenceRequired(),r.effectiveFrom(),r.effectiveTo(),r.active(),r.changeReason().trim(),actor));record(actor,p,null,r.changeReason(),ip,agent);return BereavementPolicyResponse.from(p);}
 @Transactional public BereavementPolicyResponse update(Long id,BereavementPolicyRequest r,String ip,String agent){Emp actor=requireManager();BereavementPolicy p=repository.findById(id).orElseThrow(()->BusinessException.notFound("BEREAVEMENT_POLICY_NOT_FOUND","경조 정책을 찾을 수 없습니다."));Normalized n=validate(r,id);Map<String,Object> before=snap(p);p.update(n.event(),n.relation(),r.allowedDays(),pay(r.payType()),r.evidenceRequired(),r.effectiveFrom(),r.effectiveTo(),r.active(),r.changeReason().trim(),actor);record(actor,p,before,r.changeReason(),ip,agent);return BereavementPolicyResponse.from(p);}
 private Normalized validate(BereavementPolicyRequest r,Long excludeId){String event=BereavementCatalog.normalizeEvent(r.eventType());String relation=BereavementCatalog.normalizeRelation(r.familyRelation());pay(r.payType());if(r.effectiveTo()!=null&&r.effectiveTo().isBefore(r.effectiveFrom()))throw BusinessException.badRequest("BEREAVEMENT_POLICY_PERIOD_INVALID","종료일은 시행일보다 빠를 수 없습니다.");if(Boolean.TRUE.equals(r.active())){java.time.LocalDate end=r.effectiveTo()==null?java.time.LocalDate.of(9999,12,31):r.effectiveTo();if(!repository.findOverlaps(event,relation,excludeId,r.effectiveFrom(),end).isEmpty())throw BusinessException.badRequest("BEREAVEMENT_POLICY_PERIOD_OVERLAP","같은 경조 유형·관계에 겹치는 시행기간이 있습니다.");}return new Normalized(event,relation);}
 private String pay(String v){String p=v==null?"":v.trim().toUpperCase();if(!Set.of("PAID","UNPAID").contains(p))throw BusinessException.badRequest("BEREAVEMENT_PAY_TYPE_INVALID","경조 유급 여부를 확인해 주세요.");return p;}
 private Emp requireManager(){Emp e=current.getCurrentEmp();if(!permissions.hasPermission(e,EmployeePermissionService.LEAVE_ADMIN))throw BusinessException.forbidden("LEAVE_ADMIN_REQUIRED","휴가관리자 권한이 필요합니다.");return e;}
 private Map<String,Object> snap(BereavementPolicy p){return Map.of("eventType",p.getEventType(),"familyRelation",p.getFamilyRelation(),"allowedDays",p.getAllowedDays(),"payType",p.getPayType(),"evidenceRequired",p.isEvidenceRequired(),"effectiveFrom",p.getEffectiveFrom().toString(),"active",p.isActive());}
 private void record(Emp e,BereavementPolicy p,Map<String,Object>b,String reason,String ip,String agent){audit.record(e.getEmpId(),AuditActionType.UPDATE,"bereavement_policy",p.getBereavementPolicyId(),b==null?null:mapper.valueToTree(b),mapper.valueToTree(snap(p)),ip,agent,reason,true);}
 private record Normalized(String event,String relation){}
}
