spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/groupware}
    username: ${DB_USERNAME:groupware}
    password: ${DB_PASSWORD:groupware}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

logging:
  level:
    org.hibernate.SQL: debug
