package com.kjh.groupware.domain.approval;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.kjh.groupware.domain.emp.Emp;
import com.kjh.groupware.domain.emp.EmpRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.data.jpa.repository.support.JpaRepositoryFactory;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.orm.jpa.SharedEntityManagerCreator;
import org.springframework.transaction.support.TransactionTemplate;

class AnnualLeaveSubmissionLockIntegrationTest {

    private EntityManagerFactory entityManagerFactory;
    private ExecutorService executor;
    private TransactionTemplate transaction;
    private AnnualLeaveService service;
    private Emp requester;

    @BeforeEach
    void setUp() {
        entityManagerFactory = Persistence.createEntityManagerFactory("leave-lock-test");
        executor = Executors.newFixedThreadPool(2);
        transaction = new TransactionTemplate(new JpaTransactionManager(entityManagerFactory));

        EntityManager sharedEntityManager = SharedEntityManagerCreator.createSharedEntityManager(entityManagerFactory);
        JpaRepositoryFactory repositoryFactory = new JpaRepositoryFactory(sharedEntityManager);
        EmpRepository empRepository = repositoryFactory.getRepository(EmpRepository.class);
        EmpAnnualLeaveRepository leaveRepository = repositoryFactory.getRepository(EmpAnnualLeaveRepository.class);
        AnnualLeaveLedgerRepository ledgerRepository = repositoryFactory.getRepository(AnnualLeaveLedgerRepository.class);

        service = new AnnualLeaveService(
            leaveRepository,
            ledgerRepository,
            empRepository,
            mock(com.kjh.groupware.global.security.CurrentEmpProvider.class),
            mock(com.kjh.groupware.domain.emp.EmployeePermissionService.class),
            mock(com.kjh.groupware.domain.notification.NotificationService.class),
            mock(ScheduledJobStatusService.class),
            mock(ApprovedAnnualLeaveUsageReader.class)
        );
        requester = mock(Emp.class);
        when(requester.getEmpId()).thenReturn(1L);

        transaction.executeWithoutResult(status -> {
            sharedEntityManager.createNativeQuery("""
                create table dept (
                    dept_id bigint generated by default as identity primary key,
                    dept_code varchar(30) not null unique,
                    dept_name varchar(100) not null,
                    parent_dept_id bigint,
                    sort_order integer,
                    use_yn varchar(1) not null,
                    created_at timestamp default current_timestamp not null,
                    created_by bigint,
                    updated_at timestamp,
                    updated_by bigint
                )
                """).executeUpdate();
            sharedEntityManager.createNativeQuery("""
                create table emp (
                    emp_id bigint generated by default as identity primary key,
                    emp_no varchar(30) not null unique,
                    login_id varchar(50) unique,
                    password_hash varchar(255),
                    emp_name varchar(100) not null,
                    email varchar(150),
                    phone varchar(50),
                    extension_number varchar(20),
                    dept_id bigint,
                    position_name varchar(50),
                    job_title varchar(50),
                    manager_emp_id bigint,
                    role_code varchar(30) not null,
                    hire_date date,
                    retire_date date,
                    gender_code varchar(10) not null,
                    employment_type varchar(20) not null,
                    work_category varchar(20) not null,
                    contract_start_date date,
                    contract_end_date date,
                    rehire_date date,
                    status varchar(20) not null,
                    last_login_at timestamp,
                    login_fail_count integer not null,
                    account_locked_yn varchar(1) not null,
                    account_status varchar(20) not null,
                    temp_password_expires_at timestamp,
                    must_change_password_yn varchar(1) not null,
                    password_changed_at timestamp,
                    use_yn varchar(1) not null,
                    created_at timestamp default current_timestamp not null,
                    created_by bigint,
                    updated_at timestamp,
                    updated_by bigint
                )
                """).executeUpdate();
            sharedEntityManager.createNativeQuery("""
                create table emp_annual_leave (
                    annual_leave_id bigint generated by default as identity primary key,
                    emp_id bigint not null,
                    leave_year integer not null,
                    granted_days numeric(5,1) not null,
                    adjustment_days numeric(5,1) not null,
                    adjustment_reason varchar(500),
                    manual_used_days numeric(5,1) not null,
                    auto_calculated_days numeric(5,1) not null,
                    final_days numeric(5,1) not null,
                    calculation_mode varchar(20) not null,
                    confirmation_status varchar(30) not null,
                    calculation_basis varchar(1000),
                    confirmed_at timestamp,
                    confirmed_by bigint,
                    reset_at timestamp not null,
                    updated_at timestamp,
                    updated_by bigint,
                    constraint uq_emp_annual_leave_year unique (emp_id, leave_year)
                )
                """).executeUpdate();
            sharedEntityManager.createNativeQuery("""
                create table annual_leave_ledger (
                    annual_leave_ledger_id bigint generated by default as identity primary key,
                    annual_leave_id bigint not null,
                    emp_id bigint not null,
                    leave_year integer not null,
                    transaction_type varchar(40) not null,
                    before_days numeric(5,1) not null,
                    change_days numeric(5,1) not null,
                    after_days numeric(5,1) not null,
                    reason varchar(500) not null,
                    source_type varchar(50),
                    source_id bigint,
                    created_at timestamp not null,
                    created_by bigint
                )
                """).executeUpdate();
            sharedEntityManager.createNativeQuery("""
                insert into emp (
                    emp_id, emp_no, emp_name, role_code, hire_date, gender_code, employment_type, work_category,
                    status, login_fail_count, account_locked_yn, account_status, must_change_password_yn, use_yn
                ) values (1, 'LOCK-TEST', 'Lock Test', 'USER', date '2020-01-01', 'MALE', 'REGULAR', 'FIELD',
                    'ACTIVE', 0, 'N', 'ACTIVE', 'N', 'Y')
                """).executeUpdate();
            sharedEntityManager.createNativeQuery("""
                insert into emp_annual_leave (
                    annual_leave_id, emp_id, leave_year, granted_days, adjustment_days, manual_used_days,
                    auto_calculated_days, final_days, calculation_mode, confirmation_status, reset_at
                ) values (1, 1, 2026, 15, 0, 0, 15, 15, 'AUTO', 'CONFIRMED', current_timestamp)
                """).executeUpdate();
        });
    }

    @AfterEach
    void tearDown() {
        executor.shutdownNow();
        entityManagerFactory.close();
    }

    @Test
    void concurrentSubmissionWaitsForTheEmployeeYearBalanceLock() throws Exception {
        CountDownLatch firstLockAcquired = new CountDownLatch(1);
        CountDownLatch releaseFirstTransaction = new CountDownLatch(1);
        CountDownLatch secondLockAttempted = new CountDownLatch(1);
        CountDownLatch secondLockAcquired = new CountDownLatch(1);

        Future<?> first = executor.submit(() -> transaction.executeWithoutResult(status -> {
            service.lockForSubmission(requester, 2026);
            firstLockAcquired.countDown();
            await(releaseFirstTransaction);
        }));
        assertThat(firstLockAcquired.await(5, TimeUnit.SECONDS)).isTrue();

        Future<?> second = executor.submit(() -> transaction.executeWithoutResult(status -> {
            secondLockAttempted.countDown();
            service.lockForSubmission(requester, 2026);
            secondLockAcquired.countDown();
        }));

        assertThat(secondLockAttempted.await(5, TimeUnit.SECONDS)).isTrue();
        try {
            assertThat(secondLockAcquired.await(300, TimeUnit.MILLISECONDS)).isFalse();
        } finally {
            releaseFirstTransaction.countDown();
        }
        first.get(5, TimeUnit.SECONDS);
        second.get(5, TimeUnit.SECONDS);
        assertThat(secondLockAcquired.getCount()).isZero();
    }

    private static void await(CountDownLatch latch) {
        try {
            if (!latch.await(5, TimeUnit.SECONDS)) {
                throw new AssertionError("Timed out while holding the first submission lock");
            }
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new AssertionError("Interrupted while waiting in concurrency test", ex);
        }
    }
}
