package com.kjh.groupware.domain.approval.dto;

import com.kjh.groupware.domain.approval.ApprovalEquipmentProposal;

public record EquipmentProposalResponse(
    Long approvalId,
    String workflowStage,
    String requestDeptName,
    String equipmentName,
    String requiredCompletionDate,
    String equipmentCapacity,
    String requestType,
    String moldFixtureType,
    String customerName,
    String productName,
    String usageText,
    String partName,
    String cavity,
    String material,
    String moldNo,
    String currentState,
    String requirements,
    String instructions,
    String userEconomicReview,
    String peOpinion,
    String designOpinion,
    String peEconomicReview,
    String purchaseOpinion,
    String vendorName,
    String deliveryDueDate,
    String purchaseItemName,
    String purchaseUsage,
    String quantity,
    String price,
    String purchaseNote,
    boolean attachmentContract,
    boolean attachmentQuote,
    boolean attachmentDrawing,
    boolean attachmentSpec,
    String attachmentEtc,
    Long peAssigneeEmpId,
    String peAssigneeName,
    Long purchaseAssigneeEmpId,
    String purchaseAssigneeName,
    boolean canEditUserSection,
    boolean canEditPeSection,
    boolean canEditPurchaseSection,
    boolean canAssignPe,
    boolean canAssignPurchase
) {
    public static EquipmentProposalResponse from(
        ApprovalEquipmentProposal proposal,
        boolean canEditUserSection,
        boolean canEditPeSection,
        boolean canEditPurchaseSection,
        boolean canAssignPe,
        boolean canAssignPurchase
    ) {
        return new EquipmentProposalResponse(
            proposal.getApprovalId(),
            proposal.getWorkflowStage(),
            proposal.getRequestDeptName(),
            proposal.getEquipmentName(),
            proposal.getRequiredCompletionDate(),
            proposal.getEquipmentCapacity(),
            proposal.getRequestType(),
            proposal.getMoldFixtureType(),
            proposal.getCustomerName(),
            proposal.getProductName(),
            proposal.getUsageText(),
            proposal.getPartName(),
            proposal.getCavity(),
            proposal.getMaterial(),
            proposal.getMoldNo(),
            proposal.getCurrentState(),
            proposal.getRequirements(),
            proposal.getInstructions(),
            proposal.getUserEconomicReview(),
            proposal.getPeOpinion(),
            proposal.getDesignOpinion(),
            proposal.getPeEconomicReview(),
            proposal.getPurchaseOpinion(),
            proposal.getVendorName(),
            proposal.getDeliveryDueDate(),
            proposal.getPurchaseItemName(),
            proposal.getPurchaseUsage(),
            proposal.getQuantity(),
            proposal.getPrice(),
            proposal.getPurchaseNote(),
            "Y".equals(proposal.getAttachmentContractYn()),
            "Y".equals(proposal.getAttachmentQuoteYn()),
            "Y".equals(proposal.getAttachmentDrawingYn()),
            "Y".equals(proposal.getAttachmentSpecYn()),
            proposal.getAttachmentEtc(),
            proposal.getPeAssignee() == null ? null : proposal.getPeAssignee().getEmpId(),
            proposal.getPeAssignee() == null ? null : proposal.getPeAssignee().getEmpName(),
            proposal.getPurchaseAssignee() == null ? null : proposal.getPurchaseAssignee().getEmpId(),
            proposal.getPurchaseAssignee() == null ? null : proposal.getPurchaseAssignee().getEmpName(),
            canEditUserSection,
            canEditPeSection,
            canEditPurchaseSection,
            canAssignPe,
            canAssignPurchase
        );
    }
}
